//! Embeds `assets/` into the binary.
//!
//! GPUI resolves icon and font paths through an `AssetSource`, and Starlet ships
//! as a single executable, so the tree is turned into a static slice of
//! `(path, bytes)` at build time. A build script rather than a crate keeps the
//! dependency graph free of a macro that would only ever be used here.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let assets = manifest.join("assets");
    println!("cargo:rerun-if-changed={}", assets.display());

    let mut files = Vec::new();
    collect(&assets, &assets, &mut files);
    files.sort();

    let mut out = String::from(
        "// Generated by build.rs. Paths are relative to `crates/ui/assets`.\n\
         pub static EMBEDDED: &[(&str, &[u8])] = &[\n",
    );
    for (key, path) in &files {
        out.push_str(&format!(
            "    ({key:?}, include_bytes!({:?})),\n",
            path.display()
        ));
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_assets.rs");
    std::fs::write(&dest, out).expect("write embedded_assets.rs");
}

fn collect(root: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(root, &path, out);
        } else if let Ok(rel) = path.strip_prefix(root) {
            // Forward slashes: these keys are compared against the paths
            // `gpui-component` hard-codes, which are always POSIX-style.
            let key = rel
                .components()
                .map(|c| c.as_os_str().to_string_lossy().into_owned())
                .collect::<Vec<_>>()
                .join("/");
            out.push((key, path));
        }
    }
}
